name: CI com Relatório de Testes

on:
  push:
    branches: [main]

jobs:
  testar:
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install

      - name: Executar testes
        run: npm test

      - name: Publicar relatório Mochawesome
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: relatorio-mochawesome
          path: mochawesome-report/
          retention-days: 7